Repository MastanSayyad/Visual-Sort, pull requests merged in 2024-10, with the labels that each got.

#139 terms&condition successfully changed
  Terms.html
  terms.css
Labels: enhancement, hacktoberfest-accepted

#142 Added Progress Bar for the Website Visual-Sort
  Terms.html
  index.html
  licensing.html
  privacy-policy.html
  visual.html
Labels: enhancement, hacktoberfest-accepted

#147 removed contact us section
  index.html
Labels: hacktoberfest-accepted

#154 ✔️Added Custom Scrollbar + Scrollprogress in Contributors page
  contributors.html
Labels: hacktoberfest, hacktoberfest-accepted

#159 fixed navigation tab highlight mismatch error
  index.html
Labels: hacktoberfest-accepted
