Repository MastanSayyad/Visual-Sort, pull requests merged in 2024-06, with the labels that each got.

#7 fix: footer ui
  css/style.css
  index.html
Labels: enhancement, good first issue, VSoC’24, MEDIUM

#10 Add About us section to the home page
  index.html
Labels: enhancement, VSoC’24, MEDIUM

#34 FAQ Added
  css/style.css
  index.html
  js/main.js
Labels: enhancement, VSoC’24, MEDIUM

#38 fix: minor subscribe btn ui
  index.html
Labels: VSoC’24, 1-POINT

#39 updated-visualisation-of-sorting
  Bubble.html
  index.html
  mergesort.html
  selectionsort.html
  visual.html
Labels: enhancement, good first issue, VSoC’24, HARD, BONUS

#43 Navbar Changes
  css/style.css
  index.html
Labels: enhancement, good first issue, VSoC’24, HARD, BONUS

#44 made changes in Index.html and Style.css
  index.html
  style.css
Labels: enhancement, good first issue, VSoC’24, EASY

#53 Enhancing About Us section
  about.css
  images/coding.gif
  index.html
Labels: enhancement, VSoC’24, BONUS

#52 Dropdown addition
  index.html
Labels: enhancement, VSoC’24, EASY

#56 Add Features Section (On Home Page)
  images/comparison.svg
  images/custom-input.svg
  images/multiple-sorting-algo.svg
  images/performance.svg
  images/responsive.svg
  images/speed-svgrepo-com.svg
  images/stairs-svgrepo-com.svg
  images/think-svgrepo-com.svg
  index.html
Labels: enhancement, VSoC’24, HARD

#65 Review section bug
  css/style.css
  index.html
Labels: bug, enhancement, VSoC’24, MEDIUM
