Repository MastanSayyad/Visual-Sort, pull requests merged in 2024-07, with the labels that each got.

#67 Added Login and SignUp Page
  css/login.css
  css/signup.css
  images/back-button.png
  images/login_image.png
  index.html
  login.html
  signup.html
Labels: VSoC’24, BONUS

#70 I add the privacy policy
  css/style.css
  index.html
  privacy-policy.html
Labels: VSoC’24, HARD

#71 Add AI Chatbot Feature to Enhance User Engagement on Study Website
  chatbot.html
  index.html
  main.js
  style.css
Labels: enhancement, VSoC’24, BONUS

#83 Visual sort tour guide
  visual.html
Labels: VSoC’24, BONUS

#106 Fix : bug Copyright year
  index.html
Labels: bug, VSoC’24

#118 updated the login signup and hero section
  .vscode/settings.json
  index.html
  login.html
  signup.html
Labels: VSoC’24, BONUS

#114 Comb Sort
  Algorithm/CombSort.html
  Algorithm/Combsort.js
Labels: VSoC’24, BONUS

#113 Add counting sort in the list of sorting techniques
  counting.css
  counting.html
  counting.js
  index.html
Labels: VSoC’24, BONUS

#123 Footer nav bar links working and sorting pages media query adjusted
  Algorithm/Bubble.html
  Algorithm/CombSort.html
  Algorithm/Heapsort.html
  Algorithm/Insertionsort.html
  Algorithm/Mergesort.html
  Algorithm/Quicksort.html
  Algorithm/Radixsort.html
  Algorithm/Selectionsort.html
  Algorithm/bubbles.css
  Algorithm/radix.css
  css/style.css
  index.html
Labels: VSoC’24, HARD

#130 had undo changes and add an arrow
  index.html
Labels: VSoC’24, BONUS

#132 Feature
  .env.example
  .gitignore
  Algorithm/Bubble.html
  Algorithm/CombSort.html
  Algorithm/Heapsort.html
  Algorithm/Insertionsort.html
  Algorithm/Mergesort.html
  Algorithm/Quicksort.html
  Algorithm/Radixsort.html
  Algorithm/Selectionsort.html
  chatbot.html
  contact.html
  index.html
  style.css
Labels: VSoC’24, BONUS
